### ISSUE TITLE
DL4J. Error loading own data set. numClasses and InputSplit

### ISSUE THREAD

**Issue by Piastres** [Piastres/example#1]
Unexpected exception when load own dataset. The execution of the code from [FeaturizedPreSave](https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/transferlearning/vgg16/dataHelpers/FeaturizedPreSave.java) with just a minor change in the number of samples to be taken into consideration for the neural network produce an exception of Unsupported Operation.

`numClasses = 96 `
instead of the initial 5. And own [DataSet](https://vk.com/doc108308742_467339969).

Error:

> Reader output: 96 output classes, but array.size (1) is 58 (must be equal to 1 or numClasses = 96).

Version Information:

- Deeplearning4j 1.0.0-alpha
- CUDA 8
- Java 8

Error trace:

> Exception in thread "AMDSI prefetch thread" java.lang.RuntimeException: java.lang.UnsupportedOperationException: Cannot do conversion to one hot using batched reader: 96 output classes, but array.size(1) is 58 (must be equal to 1 or numClasses = 96)
> 	at org.deeplearning4j.datasets.iterator.AsyncMultiDataSetIterator$AsyncPrefetchThread.run(AsyncMultiDataSetIterator.java:374)
> Caused by: java.lang.UnsupportedOperationException: Cannot do conversion to one hot using batched reader: 96 output classes, but array.size(1) is 58 (must be equal to 1 or numClasses = 96)
> 	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.convertWritablesBatched(RecordReaderMultiDataSetIterator.java:351)
> 	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.convertFeaturesOrLabels(RecordReaderMultiDataSetIterator.java:297)
> 	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.nextMultiDataSet(RecordReaderMultiDataSetIterator.java:270)
> 	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.next(RecordReaderMultiDataSetIterator.java:211)
> 	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:367)
> 	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:458)
> 	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:85)
> 	at org.deeplearning4j.datasets.iterator.impl.MultiDataSetIteratorAdapter.next(MultiDataSetIteratorAdapter.java:62)
> 	at org.deeplearning4j.datasets.iterator.impl.MultiDataSetIteratorAdapter.next(MultiDataSetIteratorAdapter.java:13)
> 	at org.deeplearning4j.datasets.iterator.AsyncMultiDataSetIterator$AsyncPrefetchThread.run(AsyncMultiDataSetIterator.java:346)

Some files:

- [EditLastLayerOthersFrozen](https://github.com/Piastres/example/blob/master/EditLastLayerOthersFrozen)

- [SymbolsDataSetIterator](https://github.com/Piastres/example/blob/master/SymbolsDataSetIterator)

- [pom.xml](https://github.com/Piastres/example/blob/master/pom)

- [Full log](https://github.com/Piastres/example/blob/master/log_trace)

**Comment by Piastres** [comment]
@agibsonccc, @raver119  can you help me?
